set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
Plugin 'gmarik/Vundle.vim'

Plugin 'airblade/vim-gitgutter'
Plugin 'bling/vim-airline'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'chriskempson/tomorrow-theme', { 'rtp': 'vim/' }
Plugin 'dockyard/vim-easydir'
Plugin 'dockyard/vim-savebar'
Plugin 'duggiefresh/vim-colors'
Plugin 'edkolev/tmuxline.vim'
Plugin 'ervandew/supertab'
Plugin 'fatih/vim-go'
Plugin 'garbas/vim-snipmate'
Plugin 'kchmck/vim-coffee-script'
Plugin 'kien/ctrlp.vim'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'mileszs/ack.vim'
Plugin 'mustache/vim-mode'
Plugin 'pangloss/vim-javascript'
Plugin 'Raimondi/delimitMate'
Plugin 'rking/ag.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'skwp/vim-rspec'
Plugin 'slim-template/vim-slim'
Plugin 'sunaku/vim-ruby-minitest'
Plugin 'tomtom/tlib_vim'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-haml'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-surround'
Plugin 'vim-ruby/vim-ruby'

call vundle#end()
filetype plugin indent on
colorscheme slummerville-dark
set t_Co=256
syntax on
set autoindent
set expandtab
set history=1000
set hlsearch
set ignorecase
set smartcase
set incsearch
set list listchars=tab:»·,trail:· " detect trailing whitespace
set mouse=a
set number
set cursorline
set shiftwidth=2
set showcmd
set softtabstop=2
set tabstop=2
let g:airline_powerline_fonts = 1
let g:airline_theme = 'bubblegum'
set laststatus=2 " this is for vim-airline
" Sets a timeout limit, used to kill the lag between deleting and top insert: O
set timeout timeoutlen=1000 ttimeoutlen=100
set backspace=indent,eol,start
set pastetoggle=<F7>

let mapleader = ','
let g:mapleader = ','
" Quick moves to splits and tab
nnoremap <leader>e :e <C-R>=expand('%:h').'/'<CR>
nnoremap <leader>s :sp <C-R>=expand('%:h').'/'<CR>
nnoremap <leader>v :vsp <C-R>=expand('%:h').'/'<CR>
nnoremap <leader>t :tabe <C-R>=expand('%:h').'/'<CR>
" Quick buffers
nnoremap gp :bp<CR>
nnoremap gn :bn<CR>
nnoremap gl :ls<CR>:b
nnoremap gy <C-^>
" Use CTRL to move lines up and down
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <ESC>:m .+1<CR>==gi
inoremap <C-k> <ESC>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv
" Toggle highlight
noremap <leader>h :noh<CR>
" GOTCHA IN MY CROSSHAIRS
nnoremap <leader>/ :set cursorline!<CR>
nnoremap <leader>\ :set cursorcolumn!<CR>

nmap <leader>n :NERDTreeToggle<CR> :NERDTreeMirror<CR>
let g:SuperTabDefaultCompletionType = "<c-n>"
let g:NERDSpaceDelims = 1

au BufNewFile,BufRead *.es6 set filetype=javascript

" For Syntastic
hi SpellBad ctermfg=000 ctermbg=255
hi SpellCap ctermfg=000 ctermbg=255

if executable("ag")
  set grepprg=ag\ --nogroup\ --nocolor
  let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --ignore ''.git'' --ignore ''.DS_Store'' --ignore ''node_modules'' --hidden -g ""'
endif
